[Feature] Bringing in changes from test repo
PHES-ODM/PHES-ODM pull request #264
Opened 2023-10-24 14:11 UTC by rvyuha

Contains user guides as well as the latest github actions and code for automation.
User guides and code changes are found within the R-package directory and the new action files are found within github/workflows directory.

2023-10-30 14:15 UTC, yulric requested changes
1. Lets format the file using [styler](https://github.com/r-lib/styler)
2. Rename R-Package to `release-automation`
3. Create a proper user guide which goes the steps to create a release branch and merging a release

2023-10-30 14:15 UTC, yulric commented on R-package/R/osf-interactions.R
> +    warning(
Make this a stop

2023-10-30 14:15 UTC, yulric commented on R-package/R/osf-interactions.R
> +  dictionary_path <- download_dictionary(dictionary_path, OSF_TOKEN, OSF_REPO_LINK, odm_dictionary$tmp_dictionary_directory, origin_directory = "dev-release")
I think this line and the lines that parses the dictionary should be pulled into a function called `download_dev_dictionary` in an osf module. This module would be responsible for interactions with the osf repo. This function would also be used in the `create_release_files` function.

2023-10-30 14:15 UTC, yulric commented on R-package/R/osf-interactions.R
> +stage_osf_files <- function(files_to_extract,
Rename to `create_osf_files_locally`. Stage is confusing.

2023-10-30 14:15 UTC, yulric commented on R-package/R/osf-interactions.R
> +  past_dictionary_path <- download_dictionary(past_dictionary_path, OSF_TOKEN, OSF_REPO_LINK, odm_dictionary$tmp_dictionary_directory_past_release, origin_directory = "Current Release")
This and the next lines which parses the dictionary should be pulled into a function that downloads and parses the currently released dictionary from osf. Would also be used in the `create_release_files` function.

2023-10-30 14:15 UTC, yulric commented on R-package/R/osf-interactions.R
> +archive_previous_release <- function(OSF_TOKEN, OSF_LINK, past_dictionary_version){
Should be split into functions. Once which creates the archive and one which uploads the new release.

2023-10-30 14:15 UTC, yulric commented on R-package/R/osf-interactions.R
> +  reused_storage_prefix <- file.path(getwd(),"osf-stage")
Variable only used once? Should it be stored in a variable?

2023-10-30 14:15 UTC, yulric commented on R-package/R/osf-interactions.R
> +stage_osf_files <- function(files_to_extract,
Isn't this function essentially the same as the `create_files` function.

2023-10-30 14:15 UTC, yulric commented on R-package/log
> +WARN [2023-10-10 11:10:15] Dictionary file name version does not reflect version in summary sheet
This file should be deleted? And not be put in the repo?

2023-10-30 14:31 UTC, rvyuha commented on .github/workflows/upload-dictionaries.yml
> +      - 'release/*'
Sorry was just a force of habit of putting in escape characters when using special symbols.  Pushed the fix it should be a "-".

2023-10-30 14:35 UTC, rvyuha commented on R-package/DESCRIPTION
> +    rmarkdown,
Only magrittr is being used currently. It's responsible for the R piping functions "%>%". Glue and gh are relics from previous implementations. And rmarkdown was added when I was testing some ways of building the vignettes and should also be removed.

2023-10-30 14:37 UTC, rvyuha commented on R-package/R/create-release-files.R
> +           dictionary_path = NULL,
Correct they are only used for local runs/debugging.

2023-10-30 14:38 UTC, rvyuha commented on R-package/R/create-release-files.R
> +        "Errors were detected further building cannot continue please check the log for additional info"
Agreed.

2023-10-30 15:36 UTC, rvyuha commented on R-package/R/create-release-files.R
> +    commit_files(dictionary_version, new_branch_name)
The commit_files function does also push them. I was unsure of a better name for it.

2023-10-30 15:38 UTC, rvyuha commented on R-package/R/create-release-files.R
> +    dictionary_path <- download_dictionary(dictionary_path, OSF_TOKEN, OSF_REPO_LINK, odm_dictionary$tmp_dictionary_directory, origin_directory = "dev-release")
Yes they can be combined I thought it would improve clarity if the download and retrieval of the downloaded dictionary was seperate.

2023-10-30 15:38 UTC, rvyuha commented on R-package/R/create-release-files.R
> +download_dictionary <- function(dictionary_path, OSF_TOKEN, OSF_REPO_LINK, dictionary_set_path, origin_directory){
Yes

2023-10-30 15:39 UTC, rvyuha commented on R-package/R/create-release-files.R
> +    repo_info <- osfr::osf_ls_files(repo_info)
The repo_info from line 475 is not used anywhere else, so it felt wasteful to create that variable. Piping could be used instead to ensure no mutation happens.

2023-10-30 15:40 UTC, rvyuha commented on R-package/R/create-release-files.R
> +    requested_dictionary <- osfr::osf_ls_files(requested_directory, type = "file", pattern = "ODM_dictionary_")
Variables on 477 and 478 are different variables. One is the directory of the dictionary(line 477) and the other is the link to the file itself.

2023-10-30 15:41 UTC, rvyuha commented on R-package/R/create-release-files.R
> +download_dictionary <- function(dictionary_path, OSF_TOKEN, OSF_REPO_LINK, dictionary_set_path, origin_directory){
Yeah if we combine the get_dictionary function into it.

2023-10-30 15:42 UTC, rvyuha commented on R-package/R/create-release-files.R
> +    files_sheet_formatted <-
Rows in the relation to the files sheet?

2023-10-30 15:43 UTC, rvyuha commented on R-package/R/odm-dictionary-file.R
> +odm_dictionary$version_string <- "\\{version\\}"
Yes it's currently only used within the files sheet so that makes sense.

2023-10-30 15:44 UTC, rvyuha commented on R-package/R/create-release-files.R
> +    files_sheet_formatted$name <-
Sorry what string constant?

2023-10-30 15:52 UTC, rvyuha commented on R-package/R/create-release-files.R
> +                  set_parts[names(set_parts) != single_part]
Utilizing the %in%?

2023-10-30 15:53 UTC, rvyuha commented on R-package/R/create-release-files.R
> +      } else{
Yes it should be removed.

2023-10-30 15:55 UTC, rvyuha commented on R-package/R/create-release-files.R
> +    reused_storage_prefix <- file.path(getwd(),"..")
That is correct. Initially I did not create the write_dir variable(line 329). So the logic using the write_dir variable used to be done with the reused_storage_prefix.

2023-10-30 16:05 UTC, yulric commented on .github/workflows/update-documentation.yml
> +        run: R -e 'source("R/create-release-files.R"); create_release_files(OSF_REPO_LINK = ${{secrets.OSF_REPO_LINK}}, OSF_TOKEN = ${{secrets.OSF_TOKEN}}, github_token = "${{ secrets.ACTION_TOKEN }}
Its a secret to make it easier for a user to change the link in the future. To set it it needs to be a repository secret.

2023-10-30 16:11 UTC, yulric commented on R-package/R/create-release-files.R
> +          for (single_part in partID) {
This should be using set_parts instead of partID since the former contains the parts that should be part of the final excel sheet.

2023-10-30 16:13 UTC, yulric commented on R-package/R/create-release-files.R
> +                  set_parts[names(set_parts) != single_part]
After talking to Rusty, we can just filter on the values and avoid using names or setting the names property on `set_parts`.

2026-09-17 20:19 UTC, mathew-thomson commented
Antiquated - closed

2026-09-17 20:19 UTC, closed without merging